name: GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node-version: [14.17.x]
        go-version: [^1.16.7]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: install claat command
        run: go get github.com/googlecodelabs/tools/claat
      - name: Build codelabs
        run: make build-codelabs
      - name: install node_modules
        run: npm install
      - name: Build site
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
